version: '3.7'

volumes:
  autobase-db:

services:
  autobase-postgres:
    container_name: autobase-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: autobase-db
    volumes:
      #      - ts-db:/var/lib/postgresql/data
      #      - ./data:/var/lib/postgresql/data
      - autobase-db:/var/lib/postgresql/data
    ports:
      - "5440:5432"
